# Generated by Django 6.0 on 2025-12-30 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_booking_chargingstation_contactmessage_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='station_id',
        ),
    ]
